name: Maven CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: change permission of file
      run: chmod +x awscli.sh
      
    - name: aws configure
      run: aws configure
      
    - name: runs script for creating aws infrastructure
      run : ./awscli.sh
